server:
  port: 8080

spring:
  datasource:
    username: root
    password: Root123@
    url: jdbc:mysql://127.0.0.1:3306/base_project?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
  aop:
    auto: true

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1


mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.wyc.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

operationLog: true

filesDir:
  tempDir: /BaseProjectTemp/
  uploadFileDir: /files/


