server:
  port: 8888

spring:
  datasource:
    username: root
    password: Root123@
    url: jdbc:mysql://rm-j6cl00n78p9vxywz7vo.mysql.rds.aliyuncs.com:3306/base_project?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
  aop:
    auto: true


mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.wyc.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

operationLog: true

tempDir: c:/BaseProjectTemp/


